### ISSUE TITLE
Wrong data on "Partially vaccinated" (potentially negative by tomorrow)

### ISSUE THREAD

**Issue by ostankin** [okestonia/koroonakaart#267]
I'm not sure where does the source of this data come from, but two days ago I saw a jump in "Partially vaccinated". On 23 October it [used to be 31,166](https://i.imgur.com/9hF7tKF.png), but if you look the same date [now](https://koroonakaart.ee/et), you'll see that it's 13,359. Looks like the data sources went out of sync, and now the "Partially vaccinated" number is much smaller than common sense would suggest. It can't be less than the number of first doses administered within the last three weeks - however, "Partially vaccinated" is already much smaller than that, and keeps declining rapidly. It seems like it will become negative soon :)

**Comment by atas76** [comment]
I don't know if it is related, but an endpoint for vaccination data returned 404 a couple of days ago. Seems to be OK now (by looking at the UI data).

**Comment by neuroactive** [comment]
@ostankin TEHIK released a new version of their API for vaccination data earlier this week, which changed the basis on which some of the vaccination figures are calculated. These included changes related to people who recovered from Covid and then received one dose of a two-dose vaccine. That is why the current vaccination figures on the site aren't consistent with the ones you saw previously. I am awaiting a response from TEHIK to a question I asked about a specific aspect of how the figures are compiled, but as far as I am aware the figures currently on the site are accurate.

**Comment by neuroactive** [comment]
The source data is available from this page in case it's of interest:

https://opendata.digilugu.ee/

**Comment by neuroactive** [comment]
Am reopening this issue as there is still a problem with the vaccination figures. I am investigating.

**Comment by neuroactive** [comment]
@ostankin I've fixed the issue and the "Vaccination" time series chart is now showing the correct data. Thanks for pointing out that there was a problem.
